name: CI Todo

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      DB_URL: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false
      DB_USR: sa
      DB_PWD: Senha@12345
      LOG-LEVEL: DEBUG
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Test with Maven
        run: mvn test
